---
- name: enable tomcat
  shell: /usr/sbin/a2ensite tomcat
  notify: restart apache

- name: restart apache
  service:
    name=apache2
    state=restarted

- name: restart tomcat
  service:
    name=tomcat6
    state=restarted
  notify: restart apache