---
- name: packages installed
  apt:
    pkg="{{ item }}"
    state=present
  with_items:
    - apache2
    - tomcat6
    - libapache2-mod-jk

- name: apache running
  service:
    name=apache2
    state=running
    enabled=yes