---
- name: disable default apache website
  shell: /usr/sbin/a2dissite 000-default

- name: download apache test war
  get_url:
    url="{{ war_url }}"
    dest=/var/lib/tomcat6/webapps/
    mode=0440

- name: backup original server.xml
  shell: mv /etc/tomcat6/server.xml /etc/tomcat6/server.xml.ori

- name: depot server.xml pour gestion connecteur AJP13
  copy:
    src=server.xml
    dest=/etc/tomcat6/
    owner=root
    group=root
  notify: restart tomcat

- name:  redirect apache to tomcat (jkMount)
  copy:
    src=tomcat.conf
    dest=/etc/apache2/sites-available/
    owner=root
    group=root
  notify: enable tomcat